social_network/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace social_network.Models
{
    public class UserViewModel
    {
        public string Id { get; set; }

        public string UserName { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public DateTime? BirthDate { get; set; }

        public string Gender { get; set; }

        public string HomeTown { get; set; }

        public string FullName
        {
            get
            {
                if (FirstName != null && LastName != null) {
                    return $"{FirstName} {LastName}";
                }
                else
                {
                    return UserName;
                }
            }
        }

        public IEnumerable<PostViewModel> PostModels { get; set; }
    }
}

social_network/Controllers/AvatarsController.cs
using social_network.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace social_network.Controllers
{
    public class AvatarsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
 
        public async Task<ActionResult> Show(string userId)
        {
            var avatar = await db.Avatars.FirstOrDefaultAsync(a => a.UserId == userId);
            if (avatar != null)
            {
                return File(Server.MapPath(avatar.Path), avatar.ContentType);
            }
            return File(Server.MapPath("~/Content/Images/w3images/avatar2.png"), "image/png");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

social_network/Controllers/LikesController.cs
using Microsoft.AspNet.Identity;
using social_network.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace social_network.Controllers
{
    [Authorize]
    public class LikesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [HttpPost]
        public ActionResult Create(int postId)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            if (db.Photos.Find(postId) == null)
            {
                return HttpNotFound();
            }
            if (db.Likes.Where(l => l.PostId == postId && l.VoterId == user.Id).Count() != 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var like = new Like
            {
                PostId = postId,
                VoterId = user.Id,
                VotingTime = DateTime.Now
            };
            db.Likes.Add(like);
            db.SaveChanges();
            return Json(db.Likes.Where(l => l.PostId == postId).Count());
        }

        [HttpDelete]
        public ActionResult Destroy(int postId)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var like = db.Likes.FirstOrDefault(l => l.PostId == postId && l.VoterId == user.Id);
            if (like == null)
            {
                return HttpNotFound();
            }
            db.Likes.Remove(like);
            db.SaveChanges();
            return Json(db.Likes.Where(l => l.PostId == postId).Count());
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

social_network/Controllers/PhotosController.cs
using social_network.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace social_network.Controllers
{
    public class PhotosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public async Task<ActionResult> Show(int postId)
        {
            var photo = await db.Photos.FirstOrDefaultAsync(p => p.PostId == postId);
            if (photo != null)
            {
                return File(Server.MapPath(photo.Path), photo.ContentType);
            }
            return HttpNotFound();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

social_network/Controllers/PostsController.cs
using Microsoft.AspNet.Identity;
using social_network.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace social_network.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private const int perPage = 2;

        [HttpPost]
        public ActionResult Create(NewPostViewModel newPostModel)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            if (newPostModel.Photo != null)
            {
                var post = new Post
                {
                    Body = newPostModel.Body,
                    SenderId = user.Id,
                    PublicationTime = DateTime.Now,
                };
                var photo = new Photo()
                {
                    Path = SaveFile(newPostModel.Photo, user.UserName),
                    ContentType = newPostModel.Photo.ContentType,
                    PostId = post.Id
                };
                db.Posts.Add(post);
                db.Photos.Add(photo);
                db.SaveChanges();

                var photoModel = new PostViewModel()
                {
                    Id = post.Id,
                    Body = post.Body,
                    PublicationTime = post.PublicationTime.ToString(),
                    SenderFullName = db.Users.Find(user.Id).FullName,
                    SenderId = post.SenderId,
                    Likes = db.Likes.Where(l => l.PostId == post.Id)
                };
                return Json(photoModel);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpGet]
        public ActionResult Index()
        {
            var postViewModels = db.Posts.OrderByDescending(p => p.Id).Take(perPage).ToList().Select(p => new PostViewModel()
            {
                Id = p.Id,
                Body = p.Body,
                SenderFullName = p.Sender.FullName,
                PublicationTime = p.PublicationTime.ToString(),
                Likes = db.Likes.Where(l => l.PostId == p.Id)
            });
            if (postViewModels.Count() < perPage)
            {
                ViewBag.lastId = -1;
            }
            else
            {
                ViewBag.lastId = postViewModels.Last().Id;
            }
            return View(postViewModels);
        }

        [HttpPost]
        public ActionResult More(int lastId)
        {
            var postViewModels = db.Posts.OrderByDescending(p => p.Id).Where(p => p.Id < lastId).Take(perPage).ToList().Select(p => new PostViewModel()
            {
                Id = p.Id,
                Body = p.Body,
                SenderId = p.SenderId,
                SenderFullName = p.Sender.FullName,
                PublicationTime = p.PublicationTime.ToString(),
                Likes = db.Likes.Where(l => l.PostId == p.Id)
            });
            if (postViewModels.Count() < perPage)
            {
                lastId = -1;
            }
            else
            {
                lastId = postViewModels.Last().Id;
            }
            return Json(new { lastId = lastId, posts = postViewModels }, JsonRequestBehavior.AllowGet);
        }

        [HttpDelete]
        public ActionResult Destroy(int postId)
        {
            var post = db.Posts.Find(postId);
            if (post != null)
            {
                if (User.Identity.GetUserId() != post.SenderId)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                db.Posts.Remove(post);
                db.SaveChanges();
                return new HttpStatusCodeResult(HttpStatusCode.NoContent);
            }
            else {
                return HttpNotFound();
            }
        }

        private string SaveFile(HttpPostedFileBase file, string userName)
        {
            if (file != null)
            {
                string photoName = System.IO.Path.GetFileName(file.FileName);
                string filename = Path.GetRandomFileName();
                string path = "~/PostedImages/" + userName + "/" + filename;
                string physicalPath = Server.MapPath(path);

                new FileInfo(Server.MapPath("~/PostedImages/" + userName + "/")).Directory.Create();
                file.SaveAs(physicalPath);

                return path;
            }
            return "";
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

social_network/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using social_network.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace social_network.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private RoleManager<IdentityRole> RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<RoleManager<IdentityRole>>();
            }
        }
        
        [HttpGet]
        public ActionResult Index()
        {
            return View(db.Users.AsEnumerable().OrderBy(u => u.FullName));
        }

        [HttpPost]
        public ActionResult Search(SearchModel searchModel)
        {
            IQueryable<ApplicationUser> users = UserManager.Users;
            if (!String.IsNullOrEmpty(searchModel.FirstName))
                users = users.Where(u => u.FirstName.Contains(searchModel.FirstName));
            if (!String.IsNullOrEmpty(searchModel.LastName))
                users = users.Where(u => u.LastName.Contains(searchModel.LastName));
            if (searchModel.MinAge != null)
                users = users.Where(u => DbFunctions.DiffYears(u.BirthDate, DateTime.Today) >= searchModel.MinAge);
            if (searchModel.MaxAge != null)
                users = users.Where(u => DbFunctions.DiffYears(u.BirthDate, DateTime.Today) <= searchModel.MaxAge);
            if (!String.IsNullOrEmpty(searchModel.Gender))
                users = users.Where(u => u.Gender == searchModel.Gender);
            if (!String.IsNullOrEmpty(searchModel.HomeTown))
                users = users.Where(u => u.HomeTown == searchModel.HomeTown);
            return PartialView(users.AsEnumerable().OrderBy(u => u.FullName));
        }

        [HttpGet]
        public ActionResult Show(string id)
        {
            UserViewModel userModel = null;
            ApplicationUser user = db.Users.Find(id);
            if (user != null)
            {
                userModel = new UserViewModel()
                {
                    Id = user.Id,
                    UserName = user.UserName,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    BirthDate = user.BirthDate,
                    Gender = user.Gender,
                    HomeTown = user.HomeTown
                };
                userModel.PostModels = db.Posts.Where(p => p.SenderId == user.Id).OrderByDescending(p => p.Id).Select(p => new PostViewModel()
                {
                    Id = p.Id,
                    PublicationTime = p.PublicationTime.ToString(),
                    Body = p.Body,
                    SenderId = user.Id,
                    SenderFullName = user.FullName,
                    Likes = db.Likes.Where(l => l.PostId == p.Id)
                });
                return View(userModel);
            }
            return RedirectToAction("Login", "Account");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

social_network/Views/Users/Index.cshtml
@model IEnumerable<social_network.Models.ApplicationUser>
@{
    ViewBag.Title = "Index";
}

<div class="col-sm-4 col-sm-push-8">
    <div class="w3-container w3-card-2 w3-round w3-white w3-center w3-margin">
        <div class="w3-container">
            @Html.Partial("_SearchForm")
        </div>
    </div>
</div>

<div id="results" class="col-sm-8 col-sm-pull-4">
    @Html.Partial("Search", Model)
</div>

social_network/Views/Users/Search.cshtml
@model IEnumerable<social_network.Models.ApplicationUser>

@if (Model.Count() == 0)
{
    <h1 class="text-center">Sorry, nothing was found :(</h1>
}
else
{
    <div class="w3-margin list-group user-search-result">
        @foreach (var user in Model)
        {
            <div class="list-group-item user-search-result__item">
                <img src="@Url.Action("Show", "Avatars", new { userId=user.Id })" alt="Avatar" class="user-search-result__item-avatar w3-circle w3-margin-right" style="width:60px">
                <a href="@Url.RouteUrl("DisplayUser", new { id=user.Id })"><h4>@user.FullName</h4></a>
            </div>
        }
    </div>
}

social_network/Views/Users/Show.cshtml
@using Microsoft.AspNet.Identity
@model social_network.Models.UserViewModel
@{
    ViewBag.Title = "Index";
}

<div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
        <!-- Profile -->
        <div class="w3-row-padding">
            <div class="w3-col m12">
                <div class="w3-card-2 w3-round w3-white">
                    <div class="w3-container w3-margin">
                        <h4 class="w3-center">Profile</h4>
                        <p class="w3-center"><img src="@Url.Action("Show", "Avatars", new { userId=Model.Id })" class="w3-circle" style="height:106px;width:106px" alt="Avatar"></p>
                        <hr>
                        <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i>@Model.FullName</p>
                        @if (Model.HomeTown != null)
                        {
                            <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i>@Model.HomeTown</p>
                        }
                        @if (Model.BirthDate != null)
                        {
                            <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i>@Convert.ToDateTime(Model.BirthDate).ToShortDateString()</p>
                        }
                    </div>
                </div>
                <br>

                @if (User.Identity.GetUserId() == Model.Id)
                {
                    <div class="w3-card-2 w3-round">
                        <div class="w3-accordion w3-white">
                            <a href="@Url.Action("Edit", "Account")" class="w3-btn-block w3-theme-l1 w3-left-align"><i class="fa fa-user fa-fw w3-margin-right"></i>Edit profile</a>
                        </div>
                    </div>
                }
                <br>
            </div>
        </div>
        <!-- End Left Column -->
    </div>

    <!-- Middle Column -->
    <div class="w3-col m9">

        @if (Model.Id == User.Identity.GetUserId())
        {
            <div class="w3-row-padding">
                <div class="w3-col m12">
                    <div class="w3-card-2 w3-round w3-white">
                        <div class="w3-container w3-padding w3-margin-top w3-margin-bottom">
                            @Html.Partial("../Posts/_Form")
                        </div>
                    </div>
                </div>
            </div>
        }

        <div id="posts-user@(Model.Id)">
            @if (Model.PostModels.Count() != 0)
            {
                foreach (var postModel in Model.PostModels)
                {
                    <div data-id="@postModel.Id" data-was-liked-by-current-user="@postModel.Likes.Where(l => l.VoterId == User.Identity.GetUserId()).Count().Equals(1)" class="w3-container w3-card-2 w3-white w3-round w3-margin post" id="post@(postModel.Id)">
                        <br>
                        @if (postModel.SenderId == User.Identity.GetUserId())
                        {
                            <button type="button" class="pull-right btn-link delete-post">
                                <i class="fa fa-times"></i>
                            </button>
                        }
                        <img src="@Url.Action("Show", "Avatars", new { userId=postModel.SenderId })" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px"><br>
                        <span class="w3-right w3-opacity">@postModel.PublicationTime</span>
                        <h4>@postModel.SenderFullName</h4><br>
                        <hr class="w3-clear">
                        <img class="img-responsive img-center" src="@Url.Action("Show", "Photos", new { postId=postModel.Id})" /><br>
                        <p>@postModel.Body</p>
                        <button type="button" class="w3-btn w3-theme-d1 w3-margin-bottom like-post"><i class="fa fa-thumbs-up"></i> @postModel.Likes.Count() Likes</button>
                    </div>
                }
            }
            else
            {
                <h1 id="no-posts" class="text-center">No posts :(</h1>
            }
        </div>

        <!-- End Middle Column -->
    </div>

    <!-- End Grid -->
</div>
@Html.Partial("../Posts/_PostTemplate")
<script type="text/javascript">
    String.prototype.capitalize = function () {
        return this.charAt(0).toUpperCase() + this.slice(1);
    }
    $(function () {
        var source = $("#post-template").html();
        var template = Handlebars.compile(source);
        $("#UploadPhoto").on("click", function (event) {
            event.preventDefault();
            var data = new FormData();

            var files = $("#PostForm #Photo").get(0).files;

            if (files.length > 0) {
                data.append("Photo", files[0]);
            }

            data.append("Body", $("#PostForm").find("#Body").val());

            $.ajax({
                type: "POST",
                url: "@Url.Action("Create", "Posts")",
                contentType: false,
                processData: false,
                data: data,
                success: function (data) {
                    $("#PostForm").find("textarea").val('');
                    $("#PostForm").find("input[type=file]").val('');
                    var html = template({ post: data, currentUserId: "@User.Identity.GetUserId()" });
                    $("#posts-user" + data.SenderId).find("#no-posts").remove();
                    $("#posts-user" + data.SenderId).prepend(html);
                }
            });
        });
        $(document).on("click", ".delete-post", function () {
            var element = $(this);
            $.ajax({
                type: "DELETE",
                url: "@Url.Action("Destroy", "Posts")",
                data: {
                    "postId": $(this).closest(".post").data("id"),
                },
                success: function (data) {
                    $("#posts-user@(Model.Id)").find("#post" + $(element).closest(".post").data("id")).remove();
                    if (!$(".post").length && !$("#no-posts").length) {
                        $("#posts-user@(Model.Id)").append("<h1 id='no-posts' class='text-center'>No posts :(</h1>");
                    }
                }
            });
        });
        $(document).on("click", ".like-post", function () {
            var wasLikedByCurrentUser = $(this).closest(".post").data("wasLikedByCurrentUser") == "True",
                method,
                url;
            if (wasLikedByCurrentUser) {
                method = "DELETE";
                url = "@Url.Action("Destroy", "Likes")";
            }
            else {
                method = "POST";
                url = "@Url.Action("Create", "Likes")";
            }
            var element = $(this);
            $.ajax({
                type: method,
                url: url,
                data: {
                    "postId": $(element).closest(".post").data("id"),
                },
                success: function (data) {
                    $(element).html("<i class='fa fa-thumbs-up'></i> "+data+" Likes");
                    wasLikedByCurrentUser = !wasLikedByCurrentUser;
                    $(element).closest(".post").data("wasLikedByCurrentUser", wasLikedByCurrentUser.toString().capitalize());
                }
            });
        });
    });
</script>

social_network/Views/Users/_SearchForm.cshtml
@using (Ajax.BeginForm("Search", "Users", null, new AjaxOptions { UpdateTargetId = "results" }, new { id = "SearchForm", @class = "form form-horizontal" }))
{
    <div class="form-group">
        <label class="col-xs-12">First name</label>
        <input class="form-control col-xs-12" name="FirstName" id="FirstName">
    </div>

    <div class="form-group">
        <label class="col-xs-12">Last name</label>
        <input class="form-control col-xs-12" name="LastName" id="LastName">
    </div>

    <div class="form-group">
        <label class="col-xs-12">Min age</label>
        <input type="number" class="form-control col-xs-12" name="MinAge" id="MinAge">
    </div>

    <div class="form-group">
        <label class="col-xs-12">Max age</label>
        <input type="number" class="form-control col-xs-12" name="MaxAge" id="MaxAge">
    </div>

    <div class="form-group">
        <label class="col-xs-12">Home town</label>
        <input class="form-control col-xs-12" name="HomeTown" id="HomeTown">
    </div>

    <div class="form-group">
        <label class="col-xs-12">Gender</label>
        <div class="col-xs-12">
            <label class="radio-inline">
                <input type="radio" name="Gender" id="Gender" value="Male">
                Male
            </label>
            <label class="radio-inline">
                <input type="radio" name="Gender" id="Gender" value="Female">
                Female
            </label>
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn-block w3-btn w3-theme-d1">
            Search
        </button>
    </div>
}